services:
  moxfieldpricescraper:
    image: ghcr.io/karmakamikaze/moxfield-price-scraper:latest
    container_name: MoxfieldPriceScraper
    restart: always
    environment:
      - TZ=${TIMEZONE}
      - TARGET_PRICE=${TARGET_PRICE}
      - UPDATE_FREQUENCY=${UPDATE_FREQUENCY}
      - MOXFIELD_USERNAME=${MOXFIELD_USERNAME}
      - MOXFIELD_PASSWORD=/run/secrets/MOXFIELD_PASSWORD
      - SEND_EMAIL_NOTIFICATION=${SEND_EMAIL_NOTIFICATION}
      - SENDER_EMAIL_ADDRESS=${SENDER_EMAIL_ADDRESS}
      - Sender_EMAIL_PASSWORD=/run/secrets/SENDER_EMAIL_PASSWORD
      - RECEIVER_EMAIL_ADDRESS=${RECEIVER_EMAIL_ADDRESS}
      - DECK_LIST=${DECK_LIST}
    secrets:
      - MOXFIELD_PASSWORD
      - SENDER_EMAIL_PASSWORD
    volumes:
      - ${PWD}/Data:/app/Data
      - ${PWD}/Logs:/app/Logs
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower:latest
    container_name: Watchtower
    restart: always
    environment:
      - TZ=${TIMEZONE}
      - WATCHTOWER_SCHEDULE=${WATCHTOWER_SCHEDULE}
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

secrets:
  MOXFIELD_PASSWORD:
    file: ${PWD}/secrets/moxfield_password.txt
  SENDER_EMAIL_PASSWORD:
    file: ${PWD}/secrets/sender_email_password.txt
